management.security.enabled: false

eureka:
  instance:
    preferIpAddress: false
  client:
    register-with-eureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_SERVICE_URL:http://registry/eureka/}
