server:
  port: 80
  address: 0.0.0.0

logging:
  level:
    root: WARN
#    org.springframework: INFO
#    org.springframework.cloud: DEBUG

security:
  basic:
    enabled: false
  profiles:
    active: development
